services:
  postgres_db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=feedbackdb
    volumes:
      - feedback-app-data:/var/lib/postgresql/data
    networks:
      - feedback-app-nw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  feedback_app:
    image: rosaflores/feedback-app:latest
    container_name: feedback-app
    environment:
      - DB_USER=postgres
      - DB_HOST=postgres-db
      - DB_NAME=feedbackdb
      - DB_PASSWORD=password
      - DB_PORT=5432
    networks:
      - feedback-app-nw
    ports:
      - "3030:3001"
    depends_on:
      postgres_db:
        condition: service_healthy

  feedback_app_frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: feedback-app-frontend
    networks:
      - feedback-app-nw
    ports:
      - "80:80"
    depends_on:
      - feedback_app
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf  

networks:
  feedback-app-nw:
    driver: bridge

volumes:
  feedback-app-data:



# Definition: Docker Compose 
# is a tool that allows you
# to define and run multiple Docker containers. It uses a docker-compose.yml
# file in which you can define services (containers), networks, volumes, and dependencies between them.

# Function: It orchestrates the execution of multiple containers that are part of an application.
# It is useful when your application has several services that depend on each other (e.g. a frontend, backend, database, etc.).

# Usage: Used when you have to coordinate multiple containers, 
# such as a full stack that includes a database, a backend server, and a frontend.